//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.17 at 06:27:16 PM CEST 
//


package org.forgerock.openidm.xml.persistence;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.forgerock.openidm.xml.persistence package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersistentObject_QNAME = new QName("http://openidm.forgerock.org/schema/persistence", "PersistentObject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.forgerock.openidm.xml.persistence
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistentObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openidm.forgerock.org/schema/persistence", name = "PersistentObject")
    public JAXBElement<PersistentObjectType> createPersistentObject(PersistentObjectType value) {
        return new JAXBElement<PersistentObjectType>(_PersistentObject_QNAME, PersistentObjectType.class, null, value);
    }

}
