//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.17 at 06:27:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openidm.forgerock.org/schema/persistence")
package org.forgerock.openidm.xml.persistence;
