<?xml version="1.0" encoding="UTF-8"?>
<definitions name="staging"
    targetNamespace="http://openidm.forgerock.com/xml/ns/public/model/staging-1.wsdl"
    xmlns:tns="http://openidm.forgerock.com/xml/ns/public/model/staging-1.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:abs="http://openidm.forgerock.com/xml/ns/public/model/staging-1.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <import namespace="http://openidm.forgerock.com/xml/ns/public/model/staging-1.wsdl" location="xml/ns/public/model/staging-1.wsdl"/>
    <service name="stagingService">
        <port name="stagingPortWebappClient" binding="abs:stagingBinding">
            <!-- http://localhost:${HttpDefaultPort}/stagingService/StagingService
            <soap:address location="http://localhost:${HttpDefaultPort}/stagingService/StagingService"/>
            <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
            <soap:address location="http://localhost:8080/stagingService/StagingService"/-->
            <soap:address location="http://localhost:${HttpDefaultPort}/stagingService/stagingPort"/>
        </port>
    </service>
</definitions>





